name: Deploy Azure Function

on:
  push:
    branches: ["main"]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the GitHub repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Azure CLI Login
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 3: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      # Step 4: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 5: Build
      - name: Build
        run: dotnet publish --configuration Release

      # Step 6: Deploy to Azure Function App
      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAAPP_NAME }}
          package: ${{ secrets.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
